version: "3.9"
services:
  eureka-server:
    container_name: eureka-server
    image: eureka-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - application-network

networks:
  application-network:
    external: true